#!/bin/bash
make mrproper
make ti8168_microburst_defconfig
make -j4 uImage
make -j4 modules
chmod g+rw  arch/arm/boot/uImage
cp arch/arm/boot/uImage /var/lib/tftpboot/
make INSTALL_MOD_PATH=/nfsroots/microburst modules_install
